"""
These are extra contants for the BotRoss hardware
"""

# GPIO pins
# TODO It's unclear whether these should be in GPIO.BCM or GPIO.BOARD layout

STEPPER_X_1 = 6
STEPPER_X_2 = 19
STEPPER_X_3 = 22
STEPPER_X_4 = 26

STEPPER_Y_LEFT_1 = 23
STEPPER_Y_LEFT_2 = 17
STEPPER_Y_LEFT_3 = 18
STEPPER_Y_LEFT_4 = 4

STEPPER_Y_RIGHT_1 = -1
STEPPER_Y_RIGHT_2 = -1
STEPPER_Y_RIGHT_3 = -1
STEPPER_Y_RIGHT_4 = -1

STEPPER_Z_1 = 25
STEPPER_Z_2 = 16
STEPPER_Z_3 = 20
STEPPER_Z_4 = 21
